### ISSUE TITLE
Pending documentation

### ISSUE THREAD

**Issue by lacardonap** [SwissTierrasColombia/Asistente-LADM-COL-docs#15]
Update documentation for [Asistente-LADM_COL](https://github.com/AgenciaImplementacion/Asistente-LADM_COL):

- These changes will be available in the version [1.6.3](https://github.com/AgenciaImplementacion/Asistente-LADM_COL/releases/tag/1.6.3).

  - [x] Create Right
  - [x] Create Restriction
  - [x] Create Spatial Source
  - [x] Changelog
  - [x] Check requirements plugin (QGIS, QgisModelBaker)

- These changes will be available in the version [1.6.4](https://github.com/AgenciaImplementacion/Asistente-LADM_COL/releases/tag/1.6.4).

  - [x] Create parcel
  - [ ] Create extaddress

**Comment by jonyfido** [comment]
La Documentación se encuentra en actualización a la versión 3.1.5.
https://swisstierrascolombia.github.io/Asistente-LADM-COL/index.html

**Comment by lacardonap** [comment]
Se actualiza Issue. Solo nos hace falta agregar a la documentación de como asociar una dirección al predio.  En este issue esta la explicación y el gif. https://github.com/SwissTierrasColombia/Asistente-LADM-COL/issues/422#issuecomment-792888635
