### ISSUE TITLE
Agregar sección "Roles para el Asistente LADM-COL"

### ISSUE THREAD

**Issue by gacarrillor** [SwissTierrasColombia/Asistente-LADM-COL-docs#16]
El Asistente LADM-COL funciona con base en roles. Necesitamos agregar una sección que explique este funcionamiento en detalle.

**Comment by jonyfido** [comment]
La propuesta es colocar una tabla que explique y relacione el rol y las funciones asociadas dentro del asistente así como cual _toolbar_ se le dispone al usuario en función del rol seleccionado.

**Comment by gacarrillor** [comment]
Abordado en https://github.com/SwissTierrasColombia/Asistente-LADM-COL-docs/pull/43
