### ISSUE TITLE
problemas cuando genero calidad a las construcciones 

### ISSUE THREAD

**Issue by hormisdablanco** [SwissTierrasColombia/Asistente-LADM-COL-docs#28]

**Comment by gacarrillor** [comment]
Hola @hormisdablanco, este es el repositorio de la documentación del Asistente LADM-COL. 

Por lo tanto, este issue no pertenece a este repositorio. Si quieres reportar algo al Asistente LADM-COL puedes hacerlo aquí: https://github.com/SwissTierrasColombia/Asistente-LADM-COL/issues

PERO, asegúrate de describir detalladamente qué ocurre, adjuntar un mensaje completo del error y detallar los pasos que haces para que te ocurra.
