### ISSUE TITLE
Gif building unit

### ISSUE THREAD

**Issue by juusechec** [SwissTierrasColombia/Asistente-LADM-COL-docs#6]
Use if it meets the standards.
![out__2018_05_21_1526948007](https://user-images.githubusercontent.com/4140058/40335859-8561eb7e-5d2b-11e8-9ec3-f11fe5d3c3be.gif)

**Comment by juusechec** [comment]
Used commands:
```sh
# Configure theme https://github.com/B00merang-Project/Windows-10
qt5ct
# Open QGIS
QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 SCALE_FACTOR=1 ~/bin/QGIS/build-master/output/bin/qgis --lang es

# Record GIF
WIN_ID=$(xdotool search --onlyvisible --name qgis)
xdotool windowsize $WIN_ID 1331 802
xdotool windowmove $WIN_ID 300 150
byzanz-record --duration=26 --delay=3 --x=300 --y=150 --width=1331 --height=802 out__$(date +%Y_%m_%d_%s).gif
```

**Comment by juusechec** [comment]
GNOME configurations:
![screenshot from 2018-05-21 19-22-48](https://user-images.githubusercontent.com/4140058/40336067-d958a92e-5d2c-11e8-83ff-c83a3ef0251b.png)
![screenshot from 2018-05-21 19-22-59](https://user-images.githubusercontent.com/4140058/40336068-d9745534-5d2c-11e8-8e3b-60a875b19194.png)
![screenshot from 2018-05-21 19-24-15](https://user-images.githubusercontent.com/4140058/40336069-d9908cf4-5d2c-11e8-9a31-0242788158b6.png)
![screenshot from 2018-05-21 19-25-03](https://user-images.githubusercontent.com/4140058/40336070-d9af5f9e-5d2c-11e8-96e6-af482d17bae8.png)

**Comment by gacarrillor** [comment]
Shouldn't this be a PR instead?

**Comment by juusechec** [comment]
I'll speak with @wfpinedar to show me how I can include these changes.

**Comment by wfpinedar** [comment]
No tiene nombre acore a la documentación el gif.

**Comment by juusechec** [comment]
Solve with https://github.com/AgenciaImplementacion/Asistente-LADM_COL-docs/commit/cc98261f53933d5f3b690800f5e96f38148ef01a
