### ISSUE TITLE
Aclarar rol requerido para llevar a cabo el tutorial

### ISSUE THREAD

**Issue by gacarrillor** [SwissTierrasColombia/Asistente-LADM-COL-docs#64]
En el PR #36 se habla de ejecutar la ETL de insumos Cobol.

Esta ETL no está disponible para cualquier rol, así que sería importante definir claramente en los primeros pasos del tutorial cuál es el rol con el que se estarán ejecutando las diferentes secciones del mismo.

**Comment by jhonalex06** [comment]
Solucionado en el commit a9b5d5d

**Comment by gacarrillor** [comment]
@jhonalex06, removí la parte de roles en el archivo introducción.md que introdujiste en el commit mencionado, porque de entrada confunde al lector.

Me gustó como lo dejaron de claro en la sección de Gestión de Insumos, donde llevaron al usuario a cambiar de rol al empezar la sección. Creo que esa es la manera de hacerlo.

**Comment by jhonalex06** [comment]
> @jhonalex06, removí la parte de roles en el archivo introducción.md que introdujiste en el commit mencionado, porque de entrada confunde al lector.
> 
> Me gustó como lo dejaron de claro en la sección de Gestión de Insumos, donde llevaron al usuario a cambiar de rol al empezar la sección. Creo que esa es la manera de hacerlo.

Listo si señor, muchas gracias
